name: Basic Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run a Simple Script for Job 1
      run: |
        ls -la
        pwd

  job2:
    runs-on: ubuntu-latest
    needs: job1  # job2 depends on job1

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run a Simple Script for Job 2
      run: |
        echo "This is Job 2"
        ls -la
        pwd

  job3:
    runs-on: ubuntu-latest
    needs: job1  # job3 depends on job1

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run a Simple Script for Job 3
      run: |
        echo "This is Job 3"
        ls -la
        pwd
